- project:
    templates:
      - check-requirements
      - horizon-non-primary-django-jobs
      - openstack-cover-jobs-horizon
      - openstack-lower-constraints-jobs
      - openstack-python3-zed-jobs-horizon
